<?xml version="1.0" encoding="UTF-8"?>

<!-- ELEMENT를 정의 할 때, 하위 엘리먼트의 포함관계를 명시할 때 열거형(,) 이나 선택(|) 관계를 표시 할 수 있다 -->
<!-- 내부 DTD 선언 -->

<!DOCTYPE products[
    <!ELEMENT product(prodCode, prodName, (price | quantity), company) >
        <!ELEMENT prodCode (#PCDATE) >
        <!ELEMENT prodName (#PCDATE) >
        <!ELEMENT price (#PCDATE) >
        <!ELEMENT quantity (#PCDATE) >
        <!ELEMENT company (employee, empNo)* >
        
     <!ELEMENT employee (#PCDATE) >   
     <!ELEMENT empNo (#PCDATE) >   
]>
 <!--        Product adidas = 
                new Product("S001", "슈퍼스타", 87200, 5);
        Product reebok = 
                new Product("S002", "리복 로얄 테크큐 티", 42000, 20);
        Product nike = 
                new Product("S003", "나이키 탄준 샌들", 41300, 30);
        Product crocs = 
                new Product("S004", "라이트라이드 샌들 우먼", 40200, 7);
        Product birkenstock = 
                new Product("S005", "지제 에바", 29000, 15); -->
<products>
    <product>
        <prodCode>S001</prodCode>
        <prodName>슈퍼스타</prodName>
        <price>87200</price>
        <company/>
    </product>
</products>